<?php

namespace App;

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-04-07 19:05:59
 * zip name 20220407190402_orzJJGZMH18.zip
 */

class MyApp
{
  const datetime = [
    'created_at'  => 'datetime:Y-m-d H:i:s',
    'updated_at' => 'datetime:Y-m-d H:i:s',
  ];
  const color = ["#206bc4", "#4299e1", "#4263eb", "#ae3ec9", "#d6336c", "#d63939", "#f76707", "#f59f00", "#74b816", "#2fb344", "#0ca678", "#17a2b8", "#1e293b", "#626976"];
  const debug = false;
}

/*
//app
//config/app.php -> this file

'aliases' => [
  //...
  'MyApp' => AppMyApp::class,
*/